trigger:
- main

pool:
  vmImage: ubuntu-latest   # change to 'Default' if using self-hosted

variables:
  azureServiceConnection: 'myconnection2'

stages:

- stage: Terraform
  displayName: Terraform End-to-End (PROD)

  jobs:
  - job: TerraformJob
    displayName: Init + Plan + Apply

    steps:

    - checkout: self

    # ✅ Install Terraform
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # ✅ Run Terraform
    - task: AzureCLI@2
      displayName: Terraform Init + Plan + Apply
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd env/prod

          echo "===== INIT ====="
          terraform init

          echo "===== PLAN ====="
          terraform plan -var-file="prod.tfvars" -no-color

          echo "===== APPLY ====="
          terraform apply -auto-approve -var-file="prod.tfvars"